/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner{}

// GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner struct for GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner
type GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner struct {
	Type string `json:"type"`
	Id   string `json:"id"`
}

// NewGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner instantiates a new GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner(type_ string, id string) *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner {
	this := GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInnerWithDefaults instantiates a new GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInnerWithDefaults() *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner {
	this := GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) SetId(v string) {
	o.Id = v
}

func (o GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner struct {
	value *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner
	isSet bool
}

func (v NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) Get() *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner {
	return v.value
}

func (v *NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) Set(val *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner(val *GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) *NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner {
	return &NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingRuleSetRelationshipsMatchmakingQueuesDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
