/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingTeamCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingTeamCreateRequest{}

// GameCenterMatchmakingTeamCreateRequest struct for GameCenterMatchmakingTeamCreateRequest
type GameCenterMatchmakingTeamCreateRequest struct {
	Data GameCenterMatchmakingTeamCreateRequestData `json:"data"`
}

// NewGameCenterMatchmakingTeamCreateRequest instantiates a new GameCenterMatchmakingTeamCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingTeamCreateRequest(data GameCenterMatchmakingTeamCreateRequestData) *GameCenterMatchmakingTeamCreateRequest {
	this := GameCenterMatchmakingTeamCreateRequest{}
	this.Data = data
	return &this
}

// NewGameCenterMatchmakingTeamCreateRequestWithDefaults instantiates a new GameCenterMatchmakingTeamCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingTeamCreateRequestWithDefaults() *GameCenterMatchmakingTeamCreateRequest {
	this := GameCenterMatchmakingTeamCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterMatchmakingTeamCreateRequest) GetData() GameCenterMatchmakingTeamCreateRequestData {
	if o == nil {
		var ret GameCenterMatchmakingTeamCreateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingTeamCreateRequest) GetDataOk() (*GameCenterMatchmakingTeamCreateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterMatchmakingTeamCreateRequest) SetData(v GameCenterMatchmakingTeamCreateRequestData) {
	o.Data = v
}

func (o GameCenterMatchmakingTeamCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingTeamCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGameCenterMatchmakingTeamCreateRequest struct {
	value *GameCenterMatchmakingTeamCreateRequest
	isSet bool
}

func (v NullableGameCenterMatchmakingTeamCreateRequest) Get() *GameCenterMatchmakingTeamCreateRequest {
	return v.value
}

func (v *NullableGameCenterMatchmakingTeamCreateRequest) Set(val *GameCenterMatchmakingTeamCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingTeamCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingTeamCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingTeamCreateRequest(val *GameCenterMatchmakingTeamCreateRequest) *NullableGameCenterMatchmakingTeamCreateRequest {
	return &NullableGameCenterMatchmakingTeamCreateRequest{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingTeamCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingTeamCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
