/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BetaBuildUsagesV1MetricResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BetaBuildUsagesV1MetricResponseDataInner{}

// BetaBuildUsagesV1MetricResponseDataInner struct for BetaBuildUsagesV1MetricResponseDataInner
type BetaBuildUsagesV1MetricResponseDataInner struct {
	DataPoints *BetaBuildUsagesV1MetricResponseDataInnerDataPoints `json:"dataPoints,omitempty"`
	Dimensions *BetaBuildUsagesV1MetricResponseDataInnerDimensions `json:"dimensions,omitempty"`
}

// NewBetaBuildUsagesV1MetricResponseDataInner instantiates a new BetaBuildUsagesV1MetricResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaBuildUsagesV1MetricResponseDataInner() *BetaBuildUsagesV1MetricResponseDataInner {
	this := BetaBuildUsagesV1MetricResponseDataInner{}
	return &this
}

// NewBetaBuildUsagesV1MetricResponseDataInnerWithDefaults instantiates a new BetaBuildUsagesV1MetricResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaBuildUsagesV1MetricResponseDataInnerWithDefaults() *BetaBuildUsagesV1MetricResponseDataInner {
	this := BetaBuildUsagesV1MetricResponseDataInner{}
	return &this
}

// GetDataPoints returns the DataPoints field value if set, zero value otherwise.
func (o *BetaBuildUsagesV1MetricResponseDataInner) GetDataPoints() BetaBuildUsagesV1MetricResponseDataInnerDataPoints {
	if o == nil || IsNil(o.DataPoints) {
		var ret BetaBuildUsagesV1MetricResponseDataInnerDataPoints
		return ret
	}
	return *o.DataPoints
}

// GetDataPointsOk returns a tuple with the DataPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInner) GetDataPointsOk() (*BetaBuildUsagesV1MetricResponseDataInnerDataPoints, bool) {
	if o == nil || IsNil(o.DataPoints) {
		return nil, false
	}
	return o.DataPoints, true
}

// HasDataPoints returns a boolean if a field has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInner) HasDataPoints() bool {
	if o != nil && !IsNil(o.DataPoints) {
		return true
	}

	return false
}

// SetDataPoints gets a reference to the given BetaBuildUsagesV1MetricResponseDataInnerDataPoints and assigns it to the DataPoints field.
func (o *BetaBuildUsagesV1MetricResponseDataInner) SetDataPoints(v BetaBuildUsagesV1MetricResponseDataInnerDataPoints) {
	o.DataPoints = &v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *BetaBuildUsagesV1MetricResponseDataInner) GetDimensions() BetaBuildUsagesV1MetricResponseDataInnerDimensions {
	if o == nil || IsNil(o.Dimensions) {
		var ret BetaBuildUsagesV1MetricResponseDataInnerDimensions
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInner) GetDimensionsOk() (*BetaBuildUsagesV1MetricResponseDataInnerDimensions, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInner) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given BetaBuildUsagesV1MetricResponseDataInnerDimensions and assigns it to the Dimensions field.
func (o *BetaBuildUsagesV1MetricResponseDataInner) SetDimensions(v BetaBuildUsagesV1MetricResponseDataInnerDimensions) {
	o.Dimensions = &v
}

func (o BetaBuildUsagesV1MetricResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BetaBuildUsagesV1MetricResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataPoints) {
		toSerialize["dataPoints"] = o.DataPoints
	}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	return toSerialize, nil
}

type NullableBetaBuildUsagesV1MetricResponseDataInner struct {
	value *BetaBuildUsagesV1MetricResponseDataInner
	isSet bool
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInner) Get() *BetaBuildUsagesV1MetricResponseDataInner {
	return v.value
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInner) Set(val *BetaBuildUsagesV1MetricResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaBuildUsagesV1MetricResponseDataInner(val *BetaBuildUsagesV1MetricResponseDataInner) *NullableBetaBuildUsagesV1MetricResponseDataInner {
	return &NullableBetaBuildUsagesV1MetricResponseDataInner{value: val, isSet: true}
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
