/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds{}

// BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds struct for BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds
type BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds struct {
	Links *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks `json:"links,omitempty"`
}

// NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds instantiates a new BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds() *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds {
	this := BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds{}
	return &this
}

// NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsWithDefaults instantiates a new BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsWithDefaults() *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds {
	this := BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) GetLinks() BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks {
	if o == nil || IsNil(o.Links) {
		var ret BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) GetLinksOk() (*BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks and assigns it to the Links field.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) SetLinks(v BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) {
	o.Links = &v
}

func (o BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds struct {
	value *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds
	isSet bool
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) Get() *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds {
	return v.value
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) Set(val *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds(val *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds {
	return &NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds{value: val, isSet: true}
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
