/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests{}

// GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests struct for GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests
type GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests struct {
	Data []GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsDataInner `json:"data"`
}

// NewGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests instantiates a new GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests(data []GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsDataInner) *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests {
	this := GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests{}
	this.Data = data
	return &this
}

// NewGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsWithDefaults instantiates a new GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsWithDefaults() *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests {
	this := GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) GetData() []GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsDataInner {
	if o == nil {
		var ret []GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) GetDataOk() ([]GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) SetData(v []GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequestsDataInner) {
	o.Data = v
}

func (o GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests struct {
	value *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests
	isSet bool
}

func (v NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) Get() *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests {
	return v.value
}

func (v *NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) Set(val *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests(val *GameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) *NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests {
	return &NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingRuleSetTestCreateRequestDataRelationshipsMatchmakingRequests) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
