/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks{}

// BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks struct for BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks
type BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks struct {
	GroupBy *string `json:"groupBy,omitempty"`
}

// NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks instantiates a new BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks() *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks {
	this := BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks{}
	return &this
}

// NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinksWithDefaults instantiates a new BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinksWithDefaults() *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks {
	this := BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks{}
	return &this
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) GetGroupBy() string {
	if o == nil || IsNil(o.GroupBy) {
		var ret string
		return ret
	}
	return *o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) GetGroupByOk() (*string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given string and assigns it to the GroupBy field.
func (o *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) SetGroupBy(v string) {
	o.GroupBy = &v
}

func (o BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	return toSerialize, nil
}

type NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks struct {
	value *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks
	isSet bool
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) Get() *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks {
	return v.value
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) Set(val *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks(val *BetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks {
	return &NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks{value: val, isSet: true}
}

func (v NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaBuildUsagesV1MetricResponseDataInnerDimensionsBundleIdsLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
