/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingRuleCreateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingRuleCreateRequestDataRelationships{}

// GameCenterMatchmakingRuleCreateRequestDataRelationships struct for GameCenterMatchmakingRuleCreateRequestDataRelationships
type GameCenterMatchmakingRuleCreateRequestDataRelationships struct {
	RuleSet GameCenterMatchmakingQueueCreateRequestDataRelationshipsRuleSet `json:"ruleSet"`
}

// NewGameCenterMatchmakingRuleCreateRequestDataRelationships instantiates a new GameCenterMatchmakingRuleCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingRuleCreateRequestDataRelationships(ruleSet GameCenterMatchmakingQueueCreateRequestDataRelationshipsRuleSet) *GameCenterMatchmakingRuleCreateRequestDataRelationships {
	this := GameCenterMatchmakingRuleCreateRequestDataRelationships{}
	this.RuleSet = ruleSet
	return &this
}

// NewGameCenterMatchmakingRuleCreateRequestDataRelationshipsWithDefaults instantiates a new GameCenterMatchmakingRuleCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingRuleCreateRequestDataRelationshipsWithDefaults() *GameCenterMatchmakingRuleCreateRequestDataRelationships {
	this := GameCenterMatchmakingRuleCreateRequestDataRelationships{}
	return &this
}

// GetRuleSet returns the RuleSet field value
func (o *GameCenterMatchmakingRuleCreateRequestDataRelationships) GetRuleSet() GameCenterMatchmakingQueueCreateRequestDataRelationshipsRuleSet {
	if o == nil {
		var ret GameCenterMatchmakingQueueCreateRequestDataRelationshipsRuleSet
		return ret
	}

	return o.RuleSet
}

// GetRuleSetOk returns a tuple with the RuleSet field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleCreateRequestDataRelationships) GetRuleSetOk() (*GameCenterMatchmakingQueueCreateRequestDataRelationshipsRuleSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleSet, true
}

// SetRuleSet sets field value
func (o *GameCenterMatchmakingRuleCreateRequestDataRelationships) SetRuleSet(v GameCenterMatchmakingQueueCreateRequestDataRelationshipsRuleSet) {
	o.RuleSet = v
}

func (o GameCenterMatchmakingRuleCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingRuleCreateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ruleSet"] = o.RuleSet
	return toSerialize, nil
}

type NullableGameCenterMatchmakingRuleCreateRequestDataRelationships struct {
	value *GameCenterMatchmakingRuleCreateRequestDataRelationships
	isSet bool
}

func (v NullableGameCenterMatchmakingRuleCreateRequestDataRelationships) Get() *GameCenterMatchmakingRuleCreateRequestDataRelationships {
	return v.value
}

func (v *NullableGameCenterMatchmakingRuleCreateRequestDataRelationships) Set(val *GameCenterMatchmakingRuleCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingRuleCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingRuleCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingRuleCreateRequestDataRelationships(val *GameCenterMatchmakingRuleCreateRequestDataRelationships) *NullableGameCenterMatchmakingRuleCreateRequestDataRelationships {
	return &NullableGameCenterMatchmakingRuleCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingRuleCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingRuleCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
