/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingQueueCreateRequestDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingQueueCreateRequestDataAttributes{}

// GameCenterMatchmakingQueueCreateRequestDataAttributes struct for GameCenterMatchmakingQueueCreateRequestDataAttributes
type GameCenterMatchmakingQueueCreateRequestDataAttributes struct {
	ReferenceName string `json:"referenceName"`
}

// NewGameCenterMatchmakingQueueCreateRequestDataAttributes instantiates a new GameCenterMatchmakingQueueCreateRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingQueueCreateRequestDataAttributes(referenceName string) *GameCenterMatchmakingQueueCreateRequestDataAttributes {
	this := GameCenterMatchmakingQueueCreateRequestDataAttributes{}
	this.ReferenceName = referenceName
	return &this
}

// NewGameCenterMatchmakingQueueCreateRequestDataAttributesWithDefaults instantiates a new GameCenterMatchmakingQueueCreateRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingQueueCreateRequestDataAttributesWithDefaults() *GameCenterMatchmakingQueueCreateRequestDataAttributes {
	this := GameCenterMatchmakingQueueCreateRequestDataAttributes{}
	return &this
}

// GetReferenceName returns the ReferenceName field value
func (o *GameCenterMatchmakingQueueCreateRequestDataAttributes) GetReferenceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceName
}

// GetReferenceNameOk returns a tuple with the ReferenceName field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueCreateRequestDataAttributes) GetReferenceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceName, true
}

// SetReferenceName sets field value
func (o *GameCenterMatchmakingQueueCreateRequestDataAttributes) SetReferenceName(v string) {
	o.ReferenceName = v
}

func (o GameCenterMatchmakingQueueCreateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingQueueCreateRequestDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["referenceName"] = o.ReferenceName
	return toSerialize, nil
}

type NullableGameCenterMatchmakingQueueCreateRequestDataAttributes struct {
	value *GameCenterMatchmakingQueueCreateRequestDataAttributes
	isSet bool
}

func (v NullableGameCenterMatchmakingQueueCreateRequestDataAttributes) Get() *GameCenterMatchmakingQueueCreateRequestDataAttributes {
	return v.value
}

func (v *NullableGameCenterMatchmakingQueueCreateRequestDataAttributes) Set(val *GameCenterMatchmakingQueueCreateRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingQueueCreateRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingQueueCreateRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingQueueCreateRequestDataAttributes(val *GameCenterMatchmakingQueueCreateRequestDataAttributes) *NullableGameCenterMatchmakingQueueCreateRequestDataAttributes {
	return &NullableGameCenterMatchmakingQueueCreateRequestDataAttributes{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingQueueCreateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingQueueCreateRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
