/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingQueueUpdateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingQueueUpdateRequestDataRelationships{}

// GameCenterMatchmakingQueueUpdateRequestDataRelationships struct for GameCenterMatchmakingQueueUpdateRequestDataRelationships
type GameCenterMatchmakingQueueUpdateRequestDataRelationships struct {
	RuleSet *GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet `json:"ruleSet,omitempty"`
	ExperimentRuleSet *GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet `json:"experimentRuleSet,omitempty"`
}

// NewGameCenterMatchmakingQueueUpdateRequestDataRelationships instantiates a new GameCenterMatchmakingQueueUpdateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingQueueUpdateRequestDataRelationships() *GameCenterMatchmakingQueueUpdateRequestDataRelationships {
	this := GameCenterMatchmakingQueueUpdateRequestDataRelationships{}
	return &this
}

// NewGameCenterMatchmakingQueueUpdateRequestDataRelationshipsWithDefaults instantiates a new GameCenterMatchmakingQueueUpdateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingQueueUpdateRequestDataRelationshipsWithDefaults() *GameCenterMatchmakingQueueUpdateRequestDataRelationships {
	this := GameCenterMatchmakingQueueUpdateRequestDataRelationships{}
	return &this
}

// GetRuleSet returns the RuleSet field value if set, zero value otherwise.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) GetRuleSet() GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet {
	if o == nil || IsNil(o.RuleSet) {
		var ret GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet
		return ret
	}
	return *o.RuleSet
}

// GetRuleSetOk returns a tuple with the RuleSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) GetRuleSetOk() (*GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet, bool) {
	if o == nil || IsNil(o.RuleSet) {
		return nil, false
	}
	return o.RuleSet, true
}

// HasRuleSet returns a boolean if a field has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) HasRuleSet() bool {
	if o != nil && !IsNil(o.RuleSet) {
		return true
	}

	return false
}

// SetRuleSet gets a reference to the given GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet and assigns it to the RuleSet field.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) SetRuleSet(v GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet) {
	o.RuleSet = &v
}

// GetExperimentRuleSet returns the ExperimentRuleSet field value if set, zero value otherwise.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) GetExperimentRuleSet() GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet {
	if o == nil || IsNil(o.ExperimentRuleSet) {
		var ret GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet
		return ret
	}
	return *o.ExperimentRuleSet
}

// GetExperimentRuleSetOk returns a tuple with the ExperimentRuleSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) GetExperimentRuleSetOk() (*GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet, bool) {
	if o == nil || IsNil(o.ExperimentRuleSet) {
		return nil, false
	}
	return o.ExperimentRuleSet, true
}

// HasExperimentRuleSet returns a boolean if a field has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) HasExperimentRuleSet() bool {
	if o != nil && !IsNil(o.ExperimentRuleSet) {
		return true
	}

	return false
}

// SetExperimentRuleSet gets a reference to the given GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet and assigns it to the ExperimentRuleSet field.
func (o *GameCenterMatchmakingQueueUpdateRequestDataRelationships) SetExperimentRuleSet(v GameCenterMatchmakingQueueCreateRequestDataRelationshipsExperimentRuleSet) {
	o.ExperimentRuleSet = &v
}

func (o GameCenterMatchmakingQueueUpdateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingQueueUpdateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RuleSet) {
		toSerialize["ruleSet"] = o.RuleSet
	}
	if !IsNil(o.ExperimentRuleSet) {
		toSerialize["experimentRuleSet"] = o.ExperimentRuleSet
	}
	return toSerialize, nil
}

type NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships struct {
	value *GameCenterMatchmakingQueueUpdateRequestDataRelationships
	isSet bool
}

func (v NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships) Get() *GameCenterMatchmakingQueueUpdateRequestDataRelationships {
	return v.value
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships) Set(val *GameCenterMatchmakingQueueUpdateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingQueueUpdateRequestDataRelationships(val *GameCenterMatchmakingQueueUpdateRequestDataRelationships) *NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships {
	return &NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


