/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingTeamCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingTeamCreateRequestData{}

// GameCenterMatchmakingTeamCreateRequestData struct for GameCenterMatchmakingTeamCreateRequestData
type GameCenterMatchmakingTeamCreateRequestData struct {
	Type string `json:"type"`
	Attributes GameCenterMatchmakingTeamCreateRequestDataAttributes `json:"attributes"`
	Relationships GameCenterMatchmakingRuleCreateRequestDataRelationships `json:"relationships"`
}

// NewGameCenterMatchmakingTeamCreateRequestData instantiates a new GameCenterMatchmakingTeamCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingTeamCreateRequestData(type_ string, attributes GameCenterMatchmakingTeamCreateRequestDataAttributes, relationships GameCenterMatchmakingRuleCreateRequestDataRelationships) *GameCenterMatchmakingTeamCreateRequestData {
	this := GameCenterMatchmakingTeamCreateRequestData{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewGameCenterMatchmakingTeamCreateRequestDataWithDefaults instantiates a new GameCenterMatchmakingTeamCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingTeamCreateRequestDataWithDefaults() *GameCenterMatchmakingTeamCreateRequestData {
	this := GameCenterMatchmakingTeamCreateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterMatchmakingTeamCreateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingTeamCreateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterMatchmakingTeamCreateRequestData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *GameCenterMatchmakingTeamCreateRequestData) GetAttributes() GameCenterMatchmakingTeamCreateRequestDataAttributes {
	if o == nil {
		var ret GameCenterMatchmakingTeamCreateRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingTeamCreateRequestData) GetAttributesOk() (*GameCenterMatchmakingTeamCreateRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GameCenterMatchmakingTeamCreateRequestData) SetAttributes(v GameCenterMatchmakingTeamCreateRequestDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *GameCenterMatchmakingTeamCreateRequestData) GetRelationships() GameCenterMatchmakingRuleCreateRequestDataRelationships {
	if o == nil {
		var ret GameCenterMatchmakingRuleCreateRequestDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingTeamCreateRequestData) GetRelationshipsOk() (*GameCenterMatchmakingRuleCreateRequestDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *GameCenterMatchmakingTeamCreateRequestData) SetRelationships(v GameCenterMatchmakingRuleCreateRequestDataRelationships) {
	o.Relationships = v
}

func (o GameCenterMatchmakingTeamCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingTeamCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

type NullableGameCenterMatchmakingTeamCreateRequestData struct {
	value *GameCenterMatchmakingTeamCreateRequestData
	isSet bool
}

func (v NullableGameCenterMatchmakingTeamCreateRequestData) Get() *GameCenterMatchmakingTeamCreateRequestData {
	return v.value
}

func (v *NullableGameCenterMatchmakingTeamCreateRequestData) Set(val *GameCenterMatchmakingTeamCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingTeamCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingTeamCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingTeamCreateRequestData(val *GameCenterMatchmakingTeamCreateRequestData) *NullableGameCenterMatchmakingTeamCreateRequestData {
	return &NullableGameCenterMatchmakingTeamCreateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingTeamCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingTeamCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


