/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingRuleCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingRuleCreateRequest{}

// GameCenterMatchmakingRuleCreateRequest struct for GameCenterMatchmakingRuleCreateRequest
type GameCenterMatchmakingRuleCreateRequest struct {
	Data GameCenterMatchmakingRuleCreateRequestData `json:"data"`
}

// NewGameCenterMatchmakingRuleCreateRequest instantiates a new GameCenterMatchmakingRuleCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingRuleCreateRequest(data GameCenterMatchmakingRuleCreateRequestData) *GameCenterMatchmakingRuleCreateRequest {
	this := GameCenterMatchmakingRuleCreateRequest{}
	this.Data = data
	return &this
}

// NewGameCenterMatchmakingRuleCreateRequestWithDefaults instantiates a new GameCenterMatchmakingRuleCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingRuleCreateRequestWithDefaults() *GameCenterMatchmakingRuleCreateRequest {
	this := GameCenterMatchmakingRuleCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterMatchmakingRuleCreateRequest) GetData() GameCenterMatchmakingRuleCreateRequestData {
	if o == nil {
		var ret GameCenterMatchmakingRuleCreateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleCreateRequest) GetDataOk() (*GameCenterMatchmakingRuleCreateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterMatchmakingRuleCreateRequest) SetData(v GameCenterMatchmakingRuleCreateRequestData) {
	o.Data = v
}

func (o GameCenterMatchmakingRuleCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingRuleCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGameCenterMatchmakingRuleCreateRequest struct {
	value *GameCenterMatchmakingRuleCreateRequest
	isSet bool
}

func (v NullableGameCenterMatchmakingRuleCreateRequest) Get() *GameCenterMatchmakingRuleCreateRequest {
	return v.value
}

func (v *NullableGameCenterMatchmakingRuleCreateRequest) Set(val *GameCenterMatchmakingRuleCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingRuleCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingRuleCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingRuleCreateRequest(val *GameCenterMatchmakingRuleCreateRequest) *NullableGameCenterMatchmakingRuleCreateRequest {
	return &NullableGameCenterMatchmakingRuleCreateRequest{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingRuleCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingRuleCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


