/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingQueueUpdateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingQueueUpdateRequestData{}

// GameCenterMatchmakingQueueUpdateRequestData struct for GameCenterMatchmakingQueueUpdateRequestData
type GameCenterMatchmakingQueueUpdateRequestData struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Relationships *GameCenterMatchmakingQueueUpdateRequestDataRelationships `json:"relationships,omitempty"`
}

// NewGameCenterMatchmakingQueueUpdateRequestData instantiates a new GameCenterMatchmakingQueueUpdateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingQueueUpdateRequestData(type_ string, id string) *GameCenterMatchmakingQueueUpdateRequestData {
	this := GameCenterMatchmakingQueueUpdateRequestData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewGameCenterMatchmakingQueueUpdateRequestDataWithDefaults instantiates a new GameCenterMatchmakingQueueUpdateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingQueueUpdateRequestDataWithDefaults() *GameCenterMatchmakingQueueUpdateRequestData {
	this := GameCenterMatchmakingQueueUpdateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterMatchmakingQueueUpdateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterMatchmakingQueueUpdateRequestData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GameCenterMatchmakingQueueUpdateRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GameCenterMatchmakingQueueUpdateRequestData) SetId(v string) {
	o.Id = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *GameCenterMatchmakingQueueUpdateRequestData) GetRelationships() GameCenterMatchmakingQueueUpdateRequestDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret GameCenterMatchmakingQueueUpdateRequestDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestData) GetRelationshipsOk() (*GameCenterMatchmakingQueueUpdateRequestDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *GameCenterMatchmakingQueueUpdateRequestData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given GameCenterMatchmakingQueueUpdateRequestDataRelationships and assigns it to the Relationships field.
func (o *GameCenterMatchmakingQueueUpdateRequestData) SetRelationships(v GameCenterMatchmakingQueueUpdateRequestDataRelationships) {
	o.Relationships = &v
}

func (o GameCenterMatchmakingQueueUpdateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingQueueUpdateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

type NullableGameCenterMatchmakingQueueUpdateRequestData struct {
	value *GameCenterMatchmakingQueueUpdateRequestData
	isSet bool
}

func (v NullableGameCenterMatchmakingQueueUpdateRequestData) Get() *GameCenterMatchmakingQueueUpdateRequestData {
	return v.value
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequestData) Set(val *GameCenterMatchmakingQueueUpdateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingQueueUpdateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingQueueUpdateRequestData(val *GameCenterMatchmakingQueueUpdateRequestData) *NullableGameCenterMatchmakingQueueUpdateRequestData {
	return &NullableGameCenterMatchmakingQueueUpdateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingQueueUpdateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


