/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingQueueUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingQueueUpdateRequest{}

// GameCenterMatchmakingQueueUpdateRequest struct for GameCenterMatchmakingQueueUpdateRequest
type GameCenterMatchmakingQueueUpdateRequest struct {
	Data GameCenterMatchmakingQueueUpdateRequestData `json:"data"`
}

// NewGameCenterMatchmakingQueueUpdateRequest instantiates a new GameCenterMatchmakingQueueUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingQueueUpdateRequest(data GameCenterMatchmakingQueueUpdateRequestData) *GameCenterMatchmakingQueueUpdateRequest {
	this := GameCenterMatchmakingQueueUpdateRequest{}
	this.Data = data
	return &this
}

// NewGameCenterMatchmakingQueueUpdateRequestWithDefaults instantiates a new GameCenterMatchmakingQueueUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingQueueUpdateRequestWithDefaults() *GameCenterMatchmakingQueueUpdateRequest {
	this := GameCenterMatchmakingQueueUpdateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterMatchmakingQueueUpdateRequest) GetData() GameCenterMatchmakingQueueUpdateRequestData {
	if o == nil {
		var ret GameCenterMatchmakingQueueUpdateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueUpdateRequest) GetDataOk() (*GameCenterMatchmakingQueueUpdateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterMatchmakingQueueUpdateRequest) SetData(v GameCenterMatchmakingQueueUpdateRequestData) {
	o.Data = v
}

func (o GameCenterMatchmakingQueueUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingQueueUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGameCenterMatchmakingQueueUpdateRequest struct {
	value *GameCenterMatchmakingQueueUpdateRequest
	isSet bool
}

func (v NullableGameCenterMatchmakingQueueUpdateRequest) Get() *GameCenterMatchmakingQueueUpdateRequest {
	return v.value
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequest) Set(val *GameCenterMatchmakingQueueUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingQueueUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingQueueUpdateRequest(val *GameCenterMatchmakingQueueUpdateRequest) *NullableGameCenterMatchmakingQueueUpdateRequest {
	return &NullableGameCenterMatchmakingQueueUpdateRequest{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingQueueUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingQueueUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


