/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingRuleSetTestCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingRuleSetTestCreateRequest{}

// GameCenterMatchmakingRuleSetTestCreateRequest struct for GameCenterMatchmakingRuleSetTestCreateRequest
type GameCenterMatchmakingRuleSetTestCreateRequest struct {
	Data GameCenterMatchmakingRuleSetTestCreateRequestData `json:"data"`
	Included []GameCenterMatchmakingRuleSetTestCreateRequestIncludedInner `json:"included,omitempty"`
}

// NewGameCenterMatchmakingRuleSetTestCreateRequest instantiates a new GameCenterMatchmakingRuleSetTestCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingRuleSetTestCreateRequest(data GameCenterMatchmakingRuleSetTestCreateRequestData) *GameCenterMatchmakingRuleSetTestCreateRequest {
	this := GameCenterMatchmakingRuleSetTestCreateRequest{}
	this.Data = data
	return &this
}

// NewGameCenterMatchmakingRuleSetTestCreateRequestWithDefaults instantiates a new GameCenterMatchmakingRuleSetTestCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingRuleSetTestCreateRequestWithDefaults() *GameCenterMatchmakingRuleSetTestCreateRequest {
	this := GameCenterMatchmakingRuleSetTestCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) GetData() GameCenterMatchmakingRuleSetTestCreateRequestData {
	if o == nil {
		var ret GameCenterMatchmakingRuleSetTestCreateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) GetDataOk() (*GameCenterMatchmakingRuleSetTestCreateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) SetData(v GameCenterMatchmakingRuleSetTestCreateRequestData) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) GetIncluded() []GameCenterMatchmakingRuleSetTestCreateRequestIncludedInner {
	if o == nil || IsNil(o.Included) {
		var ret []GameCenterMatchmakingRuleSetTestCreateRequestIncludedInner
		return ret
	}
	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) GetIncludedOk() ([]GameCenterMatchmakingRuleSetTestCreateRequestIncludedInner, bool) {
	if o == nil || IsNil(o.Included) {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) HasIncluded() bool {
	if o != nil && !IsNil(o.Included) {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []GameCenterMatchmakingRuleSetTestCreateRequestIncludedInner and assigns it to the Included field.
func (o *GameCenterMatchmakingRuleSetTestCreateRequest) SetIncluded(v []GameCenterMatchmakingRuleSetTestCreateRequestIncludedInner) {
	o.Included = v
}

func (o GameCenterMatchmakingRuleSetTestCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingRuleSetTestCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Included) {
		toSerialize["included"] = o.Included
	}
	return toSerialize, nil
}

type NullableGameCenterMatchmakingRuleSetTestCreateRequest struct {
	value *GameCenterMatchmakingRuleSetTestCreateRequest
	isSet bool
}

func (v NullableGameCenterMatchmakingRuleSetTestCreateRequest) Get() *GameCenterMatchmakingRuleSetTestCreateRequest {
	return v.value
}

func (v *NullableGameCenterMatchmakingRuleSetTestCreateRequest) Set(val *GameCenterMatchmakingRuleSetTestCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingRuleSetTestCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingRuleSetTestCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingRuleSetTestCreateRequest(val *GameCenterMatchmakingRuleSetTestCreateRequest) *NullableGameCenterMatchmakingRuleSetTestCreateRequest {
	return &NullableGameCenterMatchmakingRuleSetTestCreateRequest{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingRuleSetTestCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingRuleSetTestCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


