/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GameCenterMatchmakingQueueResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingQueueResponse{}

// GameCenterMatchmakingQueueResponse struct for GameCenterMatchmakingQueueResponse
type GameCenterMatchmakingQueueResponse struct {
	Data GameCenterMatchmakingQueue `json:"data"`
	Included []GameCenterMatchmakingRuleSet `json:"included,omitempty"`
	Links DocumentLinks `json:"links"`
}

// NewGameCenterMatchmakingQueueResponse instantiates a new GameCenterMatchmakingQueueResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingQueueResponse(data GameCenterMatchmakingQueue, links DocumentLinks) *GameCenterMatchmakingQueueResponse {
	this := GameCenterMatchmakingQueueResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewGameCenterMatchmakingQueueResponseWithDefaults instantiates a new GameCenterMatchmakingQueueResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingQueueResponseWithDefaults() *GameCenterMatchmakingQueueResponse {
	this := GameCenterMatchmakingQueueResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterMatchmakingQueueResponse) GetData() GameCenterMatchmakingQueue {
	if o == nil {
		var ret GameCenterMatchmakingQueue
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueResponse) GetDataOk() (*GameCenterMatchmakingQueue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterMatchmakingQueueResponse) SetData(v GameCenterMatchmakingQueue) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *GameCenterMatchmakingQueueResponse) GetIncluded() []GameCenterMatchmakingRuleSet {
	if o == nil || IsNil(o.Included) {
		var ret []GameCenterMatchmakingRuleSet
		return ret
	}
	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueResponse) GetIncludedOk() ([]GameCenterMatchmakingRuleSet, bool) {
	if o == nil || IsNil(o.Included) {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *GameCenterMatchmakingQueueResponse) HasIncluded() bool {
	if o != nil && !IsNil(o.Included) {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []GameCenterMatchmakingRuleSet and assigns it to the Included field.
func (o *GameCenterMatchmakingQueueResponse) SetIncluded(v []GameCenterMatchmakingRuleSet) {
	o.Included = v
}

// GetLinks returns the Links field value
func (o *GameCenterMatchmakingQueueResponse) GetLinks() DocumentLinks {
	if o == nil {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingQueueResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GameCenterMatchmakingQueueResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o GameCenterMatchmakingQueueResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingQueueResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Included) {
		toSerialize["included"] = o.Included
	}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

type NullableGameCenterMatchmakingQueueResponse struct {
	value *GameCenterMatchmakingQueueResponse
	isSet bool
}

func (v NullableGameCenterMatchmakingQueueResponse) Get() *GameCenterMatchmakingQueueResponse {
	return v.value
}

func (v *NullableGameCenterMatchmakingQueueResponse) Set(val *GameCenterMatchmakingQueueResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingQueueResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingQueueResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingQueueResponse(val *GameCenterMatchmakingQueueResponse) *NullableGameCenterMatchmakingQueueResponse {
	return &NullableGameCenterMatchmakingQueueResponse{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingQueueResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingQueueResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


